pipeline:
  git:
    image: plugins/git
  output:
    image: alpine
    commands:
      - tar --exclude='.git' --exclude='.drone.yml' -cjf "/var/www/builds/lumberbot-`date +%d.%m.%Y-%H.%M.%S`".tar.bz2 .
