pipeline:
  tarball:
    image: alpine
    commands:
      - tar --exclude='.git' --exclude='.drone.yml' -cjf "/tmp/lumberbot-${DRONE_TAG}.tar.bz2" .
  github_release:
    image: plugins/github-release
    files: "/tmp/lumberbot-${DRONE_TAG}.tar.bz2"
    when:
      event: tag
